Add logo, update documentation
CQCL/qujax pull request #110
Opened 2023-11-02 14:52 UTC by gamatos

- Add formatted list of gates to documentation (closes #100 )
- Summarise README.md, move some content to documentation 
    * Move examples to documentation 
    * Move "Getting started" to documentation, summarise and replace by "Quick start"
- Add logo to README.md
- Add logo to documentation
- Add some custom CSS styles to documentation
- Enable MyST parser in documentation `conf.py`
- Add MyST parser to documentation requirements

Documentation seems to be rendering fine (tested directly by running the GitHub build action). @cqc-melf would it be possible to trigger a build and deploy without releasing a new version? Some links in the `README.md` now refer to new sections in the documentation.

The MyST parser is currently being used to parse markdown files into the documentation, and will be useful in a future PR where we embed the Jupyter notebooks directly in the documentation. 

Hope everyone likes the logo!

2023-11-02 15:12 UTC, gabrielcqc approved these changes
Nice logo! :)

2023-11-02 18:24 UTC, cqc-melf requested changes
Have you taken a look on the html files generated on the CI if they all look as you are expecting?

2023-11-02 18:24 UTC, cqc-melf commented on .github/workflows/docs/requirements.txt
> +myst_parser
Do you want to add a version to this?

2023-11-02 18:29 UTC, gamatos commented
> Have you taken a look on the html files generated on the CI if they all look as you are expecting?

Yup, the files in the artifact generated by the CI action seems to be all good!

2023-11-02 18:44 UTC, gamatos commented on .github/workflows/docs/requirements.txt
> +myst_parser
Done ✅

2023-11-02 18:46 UTC, gamatos commented
> Have you taken a look on the html files generated on the CI if they all look as you are expecting?

Yup, the files in the artifact generated by the CI action seem to be all good!

Would it be possible to trigger a build and deploy without releasing a new version? Some links in the README.md now refer to new sections in the documentation.

2023-11-02 19:00 UTC, cqc-melf commented
> > Have you taken a look on the html files generated on the CI if they all look as you are expecting?
> 
> Yup, the files in the artifact generated by the CI action seem to be all good!
> 
> Would it be possible to trigger a build and deploy without releasing a new version? Some links in the README.md now refer to new sections in the documentation.

Yes that is possible, we just need to merge the changes into the main branch...

2023-11-02 19:01 UTC, cqc-melf approved these changes

2023-11-03 10:25 UTC, gamatos commented
Added one last tweak to the logo since the previous version's colours were a bit too faded, the new one is [here](https://github.com/CQCL/qujax/blob/add_logo_update_docs/docs/logo.svg).

2023-11-03 10:31 UTC, cqc-melf approved these changes

2023-11-03 11:19 UTC, merged