add get_params_to_unitarytensor_func
CQCL/qujax pull request #56
Opened 2022-11-30 12:12 UTC by SamDuffield

2022-12-01 19:56 UTC, gamatos requested changes
Looks good, I would change the assertions in the tests from `jnp.all` to `jnp.allclose` though, it is more succint and has good default values for the relative and absolute tolerance (the current `1e-5` value for an absolute tolerance might be a bit high).

2022-12-01 19:56 UTC, gamatos commented on tests/test_statetensor.py
> +    assert jnp.all(jnp.abs(unitary_jit @ zero_sv - true_sv) < 1e-5)
```suggestion
    assert jnp.allclose(unitary @ zero_sv, true_sv)
    assert jnp.allclose(unitary_jit @ zero_sv, true_sv)
```

2022-12-01 19:56 UTC, gamatos commented on tests/test_statetensor.py
>      assert jnp.all(jnp.abs(st_jit.flatten() - true_sv) < 1e-5)
```suggestion
    assert jnp.allclose(unitary @ zero_sv, true_sv)
    assert jnp.allclose(unitary_jit @ zero_sv, true_sv)
```

2022-12-01 19:56 UTC, gamatos commented on tests/test_statetensor.py
> +    assert jnp.all(jnp.abs(unitary_jit @ zero_sv - true_sv) < 1e-5)
```suggestion
    assert jnp.allclose(unitary @ zero_sv, true_sv)
    assert jnp.allclose(unitary_jit @ zero_sv, true_sv)
```

2022-12-01 19:56 UTC, gamatos commented on tests/test_statetensor.py
>      assert jnp.all(jnp.abs(st.flatten() - true_sv) < 1e-5)
```suggestion
    assert jnp.allclose(st.flatten(), true_sv)
```

2022-12-01 19:56 UTC, gamatos commented on tests/test_statetensor.py
>      assert jnp.all(jnp.abs(st.flatten() - true_sv) < 1e-5)
```suggestion
    assert jnp.allclose(st.flatten(), true_sv)
```

2022-12-01 19:56 UTC, gamatos commented on tests/test_statetensor.py
> +    assert jnp.all(jnp.abs(unitary_jit @ zero_sv - true_sv) < 1e-5)
```suggestion
    assert jnp.allclose(unitary @ zero_sv, true_sv) 
    assert jnp.allclose(unitary_jit @ zero_sv, true_sv)
```

2022-12-01 19:56 UTC, gamatos commented on tests/test_statetensor.py
>      assert jnp.all(jnp.abs(st2_2.flatten() - all_zeros_sv) < 1e-5)
```suggestion
    assert jnp.allclose(st2.flatten(), all_zeros_sv)
    assert jnp.allclose(st2_2.flatten(), all_zeros_sv)
```

2022-12-02 19:46 UTC, SamDuffield commented
> Looks good, I would change the assertions in the tests from `jnp.all` to `jnp.allclose` though, it is more succint and has good default values for the relative and absolute tolerance (the current `1e-5` value for an absolute tolerance might be a bit high).

Agreed! Much more readable

2022-12-02 20:05 UTC, gamatos approved these changes

2022-12-03 18:33 UTC, merged